version: '3.8'

services:
  api:
    build: ./api
    container_name: money-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:sqlite:/data/bank.db"
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - client

  client:
    build: ./client
    container_name: money-client
    ports:
      - "9000:80"

volumes:
  sqlite_data: